const API_BASE_URL_DEVELOPMENT = 'https://localhost:7076';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';

const  ENDPOINTS = {
    GET_ALL_POSTS: '/api/Task',
    GET_POST_BY_ID: '/api/Task',
    CREATE_POST: '/api/Task',
    UPDATE_POST: '/api/Task',
    DELETE_POST_BY_ID: '/api/Task' // -by-id 
};

const DEVELOPMENT = {
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.GET_ALL_POSTS}`,
    API_URL_GET_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.GET_POST_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.DELETE_POST_BY_ID}`
};

const PRODUCTION = {
    API_URL_GET_ALL_POSTS: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.GET_ALL_POSTS}`,
    API_URL_GET_POST_BY_ID: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.GET_POST_BY_ID}`,
    API_URL_CREATE_POST: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.CREATE_POST}`,
    API_URL_UPDATE_POST: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.UPDATE_POST}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.DELETE_POST_BY_ID}`
};

const Costants = process.env.NODE_ENV === 'development' ? DEVELOPMENT : PRODUCTION;

export default Costants; 